[109] - Create Input Number
admiral-team/admiralui-flutter pull request #144
Opened 2022-12-19 16:51 UTC by Almazovivan

https://user-images.githubusercontent.com/66259778/208477796-ac5a66df-3b2d-49d0-86fc-2f24c34c40ad.mp4
Описание задачи:
Реализовать компонент - https://www.figma.com/file/h7LytOq9qfvASRJD4uL34C/Admiral-Mobile-UI-Kit-(iOS)?node-id=10467%3A10281&t=cPGuQO1mYF4Rh5bM-4

Поле ввода с возможностью ввода числовых значений через нажатие с заданным шагом.
Number default - имеет фиксированное расстояние между кнопками с различным количеством символов;
Number secondary - ширина между кнопками зависит от ширины тестового поля.
Number textfield - компонент с textfield посередине, зависит от ширины текста

2022-12-19 17:08 UTC, Andyatkov requested changes

2022-12-19 17:08 UTC, Andyatkov commented on lib/src/widgets/controls/input_number_control/input_number_control.dart
> +class InputNuber extends StatefulWidget {
NuMber

2022-12-19 17:08 UTC, Andyatkov commented on lib/src/widgets/controls/input_number_button/input_number_button.dart
> +          width: 2,
Laygrid.halfNumber / 2

2022-12-19 17:08 UTC, Andyatkov commented on lib/src/widgets/controls/input_number_control/input_number_control.dart
> +            _numberValue.toString().replaceAll(RegExp(r'([.]*0)(?!.*\d)'), ''),
Интересное решение)

2022-12-19 17:08 UTC, Andyatkov commented on lib/src/widgets/controls/input_number_control/input_number_control.dart
> +      plusButton();
надо бы конечно реализовать такую же логику как в iOS, там с временем увеличивается прибавляемое число(вроде макс по +100)

2022-12-19 18:34 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 29
Version: 1671474805
Internal Version: 0
Short Version: 1.0.0
Branch Name: feature/109-numbers
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Flutter-iOS-Dev/releases/29

2022-12-20 09:43 UTC, Evgeniy-93 approved these changes

2022-12-20 09:48 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 30
Version: 1671529639
Internal Version: 0
Short Version: 1.0.0
Branch Name: feature/109-numbers
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Flutter-iOS-Dev/releases/30

2022-12-20 10:03 UTC, Andyatkov approved these changes

2022-12-20 10:21 UTC, timbaton commented on lib/src/widgets/controls/input_number_control/input_number_control.dart
> +    required this.onInputNumber,
мне кажется его можно сделать опциональным + поменять на что-то вроде "onChanged"

2022-12-20 10:21 UTC, timbaton commented on lib/src/widgets/controls/input_number_control/input_number_control.dart
> +  });
мне кажется, стоит добавить возможность устанавливать начальное значение типа "value=0"

2022-12-20 10:25 UTC, timbaton commented on lib/src/widgets/controls/input_number_control/input_number_control.dart
> +  Timer? timer;
> А что тут по утечки памяти? Его не надо деинитить или останавливать.(Ответ не знаю)

  @override
  void dispose() {
    timer.cancel();
    super.dispose();
  }

2022-12-20 10:43 UTC, Andyatkov commented on lib/src/widgets/controls/input_number_control/input_number_control.dart
> +  Timer? timer;
@timbaton лучший

2022-12-20 14:06 UTC, KirBorisov96 commented
Platform: iOS
Build ID: 35
Version: 1671545140
Internal Version: 0
Short Version: 1.0.0
Branch Name: feature/109-numbers
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Flutter-iOS-Dev/releases/35

2022-12-21 17:27 UTC, timbaton approved these changes

2022-12-22 06:32 UTC, merged