[8] - Create Primary Button
admiral-team/admiralui-flutter pull request #15
Opened 2022-07-28 17:39 UTC by Almazovivan

Реализация компонента Primary Button

2022-07-29 10:28 UTC, timbaton approved these changes

2022-07-29 10:28 UTC, timbaton commented on pubspec.yaml
> +assets:
надо будет потом удалить, тк иконки подтянутся

2022-07-29 11:23 UTC, ton252 commented on pubspec.yaml
> +assets:
Да, это раз. И никогда не добавляй иконки в формате jpg. png / svg / pdf

2022-07-29 11:37 UTC, KirBorisov96 approved these changes

2022-07-29 11:40 UTC, ton252 requested changes

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +    // var theme = AppThemeProvider.of(context);
мертвый код

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +class PrimaryButtonWidget extends StatefulWidget {
Не забываем про документацию. Посмотри, как это делается во Flutter. Сам текст и описание можно копипастить из iOS/android проектов, но дока быть должна

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +class PrimaryButtonWidget extends StatefulWidget {
Избегай избыточных названий. Если кнопка - PrimaryButton. Слово Widget избыточно

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button_scheme.dart
> +  // const FontWrapper({
мертвый кот 🐈

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button_scheme.dart
> +  TextStyle toTextStyle(double opacity) {
Такое будет часто встречаться в других компонентах, надо подумать, мб как-то вынести? Или еще вопрос, а зачем было плодить столько сущностей textColor / fontFamily и т.д, если у тебя и так уже есть TextStyle? Почему бы просто не сделать свойство final TextStyle textStyle = ...;

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/button_size_type.dart
> +enum ButtonSizeType { small, big, medium }
Это так автоформаттер сработал? я бы лучше на каждой строке enum делал

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/icon_direction.dart
> +enum IconDirection { left, right }
Аналогично

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +  @override
отступ между переменными и функциями

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +  var scheme = PrimaryButtoScheme();
почему var? и почему она у тебя публичная?

2022-07-29 11:40 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +    if (widget.icon != null && widget.direction == IconDirection.left) {
1) очень много дублирующего кода внутри, подумай, как это сделать поудобнее
2) не надо код, как в Swift выносить в отдельную функцию, тут придется его оборачивать тогда в отдельный StatelessWidget, потому что иначе это ударит по производительности. Весь код, который выносишь в хочется вынести в функцию, лучше вынести в отдельный  StatelessWidget

2022-08-02 10:35 UTC, Almazovivan commented on pubspec.yaml
> +assets:
А какие тогда иконки будут, у меня так и не получилось загрузить свое изображение

2022-08-02 10:58 UTC, Almazovivan commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +  var scheme = PrimaryButtoScheme();
Мы обычно даем публичный доступ к схеме

2022-08-03 14:33 UTC, KirBorisov96 submitted a review, later dismissed

2022-08-03 15:03 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button.dart
> +    var scheme = widget.scheme ?? PrimaryButtonScheme();
небольшая дотошность по оптимизации: PrimaryButtonScheme() будет создаваться каждый раз, когда будет перебилжеваться виджет build(BuildContext context). Лучше ее задать в методе initState и потом уже  заюзать. Ну и в целом ее можно в инициализаторе, как дефолтное значение передать

2022-08-03 15:06 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button_scheme.dart
> +  late Color buttonDisableColor = const Color(0xFF3A83F1).withOpacity(opacity);
вот эта конструкция меня не впирает, late явно не нужен. Вот поменяешь потом opacity а цвета же тут не поменяются. Ты либо просто уже проставь такой-то цвет с 0.6 opacity, либо opacity из этой схемы уже в самом компоненте юзай

2022-08-03 15:07 UTC, ton252 commented on lib/src/Widgets/Controlls/PrimaryButton/primary_button_scheme.dart
> +  TextStyle toNormalTextStyle() {
без to

2022-08-03 15:07 UTC, ton252 submitted a review, later dismissed

2022-08-08 07:37 UTC, ton252 approved these changes

2022-08-08 11:58 UTC, KirBorisov96 approved these changes

2022-08-08 13:25 UTC, merged