[3] - Added theming: ColorPalette and FontPalette.
admiral-team/admiralui-flutter pull request #37
Opened 2022-08-15 21:33 UTC by timbaton

2022-08-16 12:54 UTC, ton252 requested changes

2022-08-16 12:54 UTC, ton252 commented on lib/theme/app_theme_provider.dart
> +    return context
очень плохо читается

2022-08-16 12:54 UTC, ton252 commented on lib/theme/app_theme.dart
> +const lightTheme = AppTheme(
я бы не стал делать их отдельно в воздухе константами, лучше к неймспейсу их привязать AppTheme

2022-08-16 12:54 UTC, ton252 commented on lib/tools/templates/ColorPalette.txt
> +import 'package:admiralui_flutter/theme/color_wrapper.dart';
лучше название не txt ставить - из этого не понятно, что это шаблон. Обычно есть конвенция нейминга, условно *.template, лучше посмотреть как в go принято

2022-08-16 12:54 UTC, ton252 commented on lib/theme/font_palette.dart
> +  final FontWrapper subhead3;
Не очень мне нравится Wrapper, лучше просто AdmiralFont или еще лучше **AFont**.  Потому что по факту это модельный объект, который хранит параметры шрифта. Warapper подразумевает, что он то-то оборачивает, но по факту он ничего не оборачивает

2022-08-16 12:54 UTC, ton252 commented on lib/theme/color_wrapper.dart
> +  const ColorWrapper(this.value);
Аналогично, не нравится Wrapper

2022-08-16 12:54 UTC, ton252 commented on pubspec.yaml
> +    - family: Roboto
А откуда у нас шрифт Roboto появился? Вообще же мы SF везде юзаем

2022-08-16 16:30 UTC, KirBorisov96 approved these changes

2022-08-16 18:19 UTC, timbaton commented on pubspec.yaml
> +    - family: Roboto
Figma возвращает Roboto

2022-08-29 20:17 UTC, ton252 requested changes
Разбить на 3-4 пр

2022-09-06 10:59 UTC, KirBorisov96 approved these changes

2022-09-06 12:42 UTC, closed without merging