[50] - add radio button component
admiral-team/admiralui-flutter pull request #70
Opened 2022-09-26 17:42 UTC by timbaton

2022-10-04 06:49 UTC, ton252 requested changes

2022-10-04 06:49 UTC, ton252 commented on lib/src/widgets/radio_button/radio_button.dart
> +    this.radioColor,
опять же где схемы?

2022-10-04 06:49 UTC, ton252 commented on lib/src/widgets/radio_button/radio_button.dart
> +      child: Row(
вот этот блок кода как-то плохо читается

2022-10-04 06:49 UTC, ton252 commented on lib/src/widgets/radio_button/radio_group.dart
> +class _RadioGroup extends State<RadioGroup> {
Опять же State

2022-10-04 11:13 UTC, KirBorisov96 approved these changes

2022-10-04 11:21 UTC, Andyatkov commented on lib/layout/layout_grid.dart
> +  static double twoFifthsModule = halfModule * 5;
Зачем это нужно?

2022-10-04 11:21 UTC, Andyatkov commented on lib/src/widgets/radio_button/radio_group.dart
> +    this.verticalPadding = 10,
По идеи должно быть кратно 8

2022-11-10 07:43 UTC, KirBorisov96 approved these changes

2022-11-16 00:12 UTC, merged