[41] - add switcher component
admiral-team/admiralui-flutter pull request #71
Opened 2022-09-26 22:29 UTC by timbaton

2022-10-04 06:39 UTC, ton252 commented on lib/src/widgets/switcher.dart
> +class _Switcher extends State<Switcher> {
Не знаю по-моему по конвенции флаттер State нужно писать в названии

2022-10-04 06:39 UTC, ton252 commented on lib/src/widgets/switcher.dart
> +  const Switcher({
почему в конструкторе передаешь все цвета а не схему цветовую?

2022-10-04 06:48 UTC, ton252 requested changes
Поправить комменты

2022-10-04 12:02 UTC, Almazovivan approved these changes

2022-11-10 07:43 UTC, KirBorisov96 approved these changes

2022-11-15 12:00 UTC, merged