[73] - add CheckBox component
admiral-team/admiralui-flutter pull request #77
Opened 2022-09-27 20:56 UTC by timbaton

2022-10-04 06:46 UTC, ton252 requested changes

2022-10-04 06:46 UTC, ton252 commented on lib/src/widgets/checkbox/checkbox.dart
> +        color: value ? Colors.white : Colors.transparent,
почему цвет берется из общих цветов?

2022-10-04 06:46 UTC, ton252 commented on lib/src/widgets/checkbox/checkbox_title.dart
> +class _CheckBox extends State<CheckBoxTitle> {
Опять же по конвенции вроде как Стейт указывается в названии, проверь

2022-10-04 11:16 UTC, KirBorisov96 approved these changes

2022-10-04 11:19 UTC, Andyatkov commented on lib/src/widgets/checkbox/checkbox.dart
> +      duration: const Duration(milliseconds: 650),
magic const

2022-10-04 12:00 UTC, Almazovivan approved these changes

2022-11-10 07:41 UTC, KirBorisov96 commented on lib/src/widgets/checkbox/checkbox.dart
> +  final Color fillColor;
Cхема цветовая нужна здесь ?

2022-11-10 07:42 UTC, KirBorisov96 commented on lib/src/widgets/checkbox/checkbox_group.dart
> +  final Color? checkBoxColor;
здесь тоже про схему

2022-11-10 07:42 UTC, KirBorisov96 approved these changes

2022-11-10 07:44 UTC, KirBorisov96 requested changes
нужны цветовые схемы

2022-11-10 12:20 UTC, timbaton commented on lib/src/widgets/checkbox/checkbox.dart
> +  final Color fillColor;
Мне кажется, что пока в компоненте 1 цвет не стоит его усложнять цветовой схемой. Но можем обсудить с командой

2022-11-16 12:22 UTC, timbaton commented on lib/src/widgets/checkbox/checkbox.dart
> +  final Color fillColor;
Этот компонент является внутренним, который извне принимает цвет, в зависимости от состояния isEnabled

2022-11-30 18:13 UTC, KirBorisov96 approved these changes

2022-12-02 12:20 UTC, Andyatkov approved these changes

2022-12-04 15:21 UTC, merged