[85] - Added Logo Tabs
admiral-team/admiralui-flutter pull request #88
Opened 2022-11-14 07:05 UTC by KirBorisov96

2022-11-16 00:13 UTC, timbaton approved these changes

2022-11-22 14:07 UTC, Evgeniy-93 approved these changes

2022-11-22 14:10 UTC, Evgeniy-93 approved these changes

2022-11-22 17:00 UTC, timbaton commented on lib/src/widgets/tabs/logo_tabs/logo_tabs.dart
> +        child: Column(
если не будет TabBarView, то надо тогда ручку дать onSelected. Думаю, эту ручку и в StandardTabs надо будет добавить, но это тоже уже мой косяк

2022-12-02 12:27 UTC, Andyatkov requested changes

2022-12-02 12:27 UTC, Andyatkov commented on lib/src/widgets/tabs/logo_tabs/logo_tabs.dart
> +  const LogoTabs({
А как сделать по дефолту, чтобы 2 индекс был залектан?

2022-12-07 23:19 UTC, timbaton commented on lib/src/widgets/tabs/logo_tabs/logo_tabs_scheme.dart
> +  late AFont unselectedLabelFont;
для чего нам в этом компоненте Font?

2022-12-12 09:41 UTC, Andyatkov commented on lib/src/widgets/tabs/logo_tabs/logo_tabs.dart
> +            for (int i = 0; i < widget.images.length; i++) ...<Widget>[
Можно вот так

 widget.images.forEachIndexed((i, image) {
    print('index: $i, element: $image');
  });

2022-12-12 10:01 UTC, merged